Repository legesher/legesher-translations, pull requests merged in 2019-10, with the labels that each got.

#8 update README with new project list: legesher-pride :tada:
  README.md
Labels: Hacktoberfest

#19 Add locale folder for translation guides
  app/routes/index.js
  app/routes/translation-routes.js
  config/dialects.json
  config/keywords.json
  config/programming-languages.json
  locale/dialect-list.yml
  locale/en.yml
  locale/language-keyword-template.yml
  locale/pt.yml
  locale/uk.yml
  package-lock.json
  package.json
  server.js
Labels: Hacktoberfest

#21 Polish translation
  pl.yml
Labels: Hacktoberfest, Type: Translation

#26 Added italian python translation
  locale/it.yml
Labels: Dialect: Italian, Hacktoberfest

#23 Portuguese translation @katherinefernandes
  app/routes/index.js
  app/routes/translation-routes.js
  config/dialects.json
  config/keywords.json
  config/programming-languages.json
  locale/dialect-list.yml
  locale/en.yml
  locale/language-keyword-template.yml
  locale/pt.yml
  locale/uk.yml
  package-lock.json
  package.json
  server.js
Labels: Dialect: Portuguese, Hacktoberfest, Status: Revision Needed, Technical Experience: None, 🌍 Opportunity: Translation

#44 [#34] Typo fix and removed comments in language-keyword-template
  locale/language-keyword-template.yml
Labels: 🐛 Opportunity: Bug

#67 Add polish javascript translation
  pl.yml
Labels: Dialect: Polish, Language: Java, Language: Javascript, Status: Completed, 🌍 Opportunity: Translation

#69 Polish verify python
  pl.yml
Labels: Dialect: Polish, Language: Python

#70 Add typescript translation
  pl.yml
Labels: Dialect: Polish, Language: Typescript

#71 Added translations for Python Built-in functions
  locale/ar.yml
Labels: Dialect: Arabic

#66 Reviewed the German translation of Python
  de.yaml
Labels: Dialect: German

#73 Add 2nd verification for Polish translation of Python
  pl.yml
Labels: Dialect: Polish

#63 Add updated translations for Python
  locale/uk.yml
Labels: Dialect: Ukrainian

#77 Revision of python keywords translation (es)
  locale/es.yml
Labels: Dialect: Spanish, 🌍 Opportunity: Translation

#78 ukrainian-translation
  locale/uk.yml
Labels: Dialect: Ukrainian, 🌍 Opportunity: Translation

#79 third round of revision
  locale/es.yml
Labels: Dialect: Spanish, 🌍 Opportunity: Translation

#65 #43 review german translation
  de.yaml
Labels: Dialect: German

#85 added tagalog translations (atom,agda,c,javascript)
  locale/tl.yml
Labels: Dialect: Tagalog, 📖 Opportunity: Documentation

#89 docs: update readme to contain current languages in active development
  README.md
Labels: 📖 Opportunity: Documentation

#94 Update language-conventions link in the README.md
  README.md
Labels: 📖 Opportunity: Documentation

#93 Review italian python translation
  locale/it.yml
Labels: Dialect: Italian, Language: Python, 🌍 Opportunity: Translation

#96 Added translation to built-in functions
  locale/xh.yml
Labels: Dialect: Xhosa, 🌍 Opportunity: Translation

#98 Added welsh language translations for Python
  locale/cy.yml
Labels: Dialect: Welsh, 🌍 Opportunity: Translation

#101 review german translation. Issue (#11)
  de.yaml
Labels: Dialect: German, Language: C, Language: Java, Language: Python, 🌍 Opportunity: Translation

#95 Review Tagalog Translation (Python)
  .all-contributorsrc
  README.md
  locale/tl.yml
Labels: Dialect: Tagalog, 🌍 Opportunity: Translation

#104 Portuguese translation
  locale/pt.yml
Labels: Dialect: Portuguese, Language: Bash, Language: Golang, Language: Java, Language: Ruby, 🌍 Opportunity: Translation

#107 Created CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Hacktoberfest, 📖 Opportunity: Documentation

#106 Add more contributors from Hacktoberfest
  .all-contributorsrc
  README.md
Labels: 📆 Opportunity: Project Management

#112 add python translation in Gujarati
  locale/dialect-list.yml
  locale/gu.yml
Labels: 🌍 Opportunity: Translation

#117 added and edited tr.yml
  locale/tr.yml
Labels: Dialect: Turkish, 🌍 Opportunity: Translation

#118 Review German translations for Python
  de.yaml
Labels: Dialect: German, 🌍 Opportunity: Translation
