Repository legesher/legesher-translations, pull requests merged in 2020-10, with the labels that each got.

#137 docs: Review of french python translation.
  locale/fr.yml
Labels: Dialect: French, Hacktoberfest, Language: Python, 🌍 Opportunity: Translation

#138 Review Dialect: Spanish (Python)
  locale/es.yml
Labels: Dialect: Spanish, Hacktoberfest, Language: Python, 🌍 Opportunity: Translation

#139 Review Dialect: Arabic (Python)
  locale/ar.yml
Labels: Dialect: Arabic, Hacktoberfest, Language: Python, 🌍 Opportunity: Translation

#140 te.yml
  tel.yml
Labels: Dialect: Telugu, Hacktoberfest, Language: Python, 🌍 Opportunity: Translation

#141 feat: initial Hebrew dialect added
  locale/he.yml
Labels: Dialect: Hebrew, Hacktoberfest, Language: Atom, 🌍 Opportunity: Translation

#142 Review Dialect: Portuguese (Python)
  locale/pt.yml
Labels: Dialect: Portuguese, Hacktoberfest, Language: Python, 🌍 Opportunity: Translation

#143 Add 3rd review for Polish translation of Python
  pl.yml
Labels: Dialect: Polish, Hacktoberfest, Language: Python, 🌍 Opportunity: Translation

#145 Review Dialect: Spanish (Python)
  locale/es.yml
Labels: Dialect: Spanish, Hacktoberfest, Language: Python, 🌍 Opportunity: Translation

#146 Review: German translation for Python
  locale/de.yaml
Labels: Dialect: German, Hacktoberfest, Language: Python, 🌍 Opportunity: Translation

#148 some more hindi translations
  locale/hi.yml
Labels: Dialect: Hindi, Hacktoberfest, Language: Atom, 🌍 Opportunity: Translation

#149 Review Dialect: Hebrew (Python)
  README.md
  locale/he.yml
Labels: Dialect: Hebrew, Hacktoberfest, Language: Python, 🌍 Opportunity: Translation

#152 Review Dialect: Russian (Python) (Issue #38)
  locale/ru.yml
Labels: Dialect: Russian, Hacktoberfest, Language: Python, 🌍 Opportunity: Translation

#154 Add Indonesian language
  README.md
  locale/id.yml
Labels: Dialect: Indonesian, Hacktoberfest, Language: Python, 🌍 Opportunity: Translation

#151 Hindi translation
  locale/hi.yml
Labels: Dialect: Hindi, Hacktoberfest, Language: Agda, Language: Atom, Language: Bash, Language: C, Language: Golang, Language: Node, Language: Python, 🌍 Opportunity: Translation

#150 feat: updated README.md
  README.md
Labels: Hacktoberfest, 📖 Opportunity: Documentation

#158 Review Dialect: Indonesian (Python)
  locale/id.yml
Labels: Dialect: Indonesian, Hacktoberfest, Language: Python, 🌍 Opportunity: Translation

#160 Javascript portuguese translation
  locale/pt.yml
Labels: Dialect: Portuguese, Hacktoberfest, Language: JavaScript, 🌍 Opportunity: Translation

#161 feat: Add Finnish Python keyword translations
  locale/fi.yml
Labels: Dialect: Finnish, Hacktoberfest, Language: Python, 🌍 Opportunity: Translation

#163 added keywords for hindi translation for js
  locale/hi.yml
Labels: Dialect: Hindi, Hacktoberfest, Language: JavaScript, 🌍 Opportunity: Translation

#165 update contributors and README
  .all-contributorsrc
  README.md
  locale/dialect-list.yml
Labels: Hacktoberfest, 📖 Opportunity: Documentation, 🚧 Opportunity: Maintenance

#166 Add keyword file translation in greek (python)
  locale/el.yml
Labels: Hacktoberfest, Language: Python, 🌍 Opportunity: Translation

#167 Added Dutch translation for Python and Atom keywords
  locale/nl.yml
Labels: Dialect: Dutch, Hacktoberfest, Language: Atom, Language: Python, 🌍 Opportunity: Translation
