Repository legesher/legesher-translations, pull requests merged in 2021-11, with the labels that each got.

#249 fix: #249 Editing Grammatical errors
  README.md
Labels: Hacktoberfest-Accepted, 📖 Opportunity: Documentation

#282 Hebrew Translation Atom
  locale/he.yml
Labels: Hacktoberfest-Accepted, 🌍 Opportunity: Translation, Language: Atom, Dialect: Hebrew

#274 review Built-In Functions in python
  locale/gu.yml
Labels: Language: Python, Hacktoberfest-Accepted, 🌍 Opportunity: Translation, Dialect: Gujarati

#283 Gujarati translations - Updated till C programming Language #113
  locale/gu.yml
Labels: Hacktoberfest-Accepted, 🌍 Opportunity: Translation, Language: Atom, Language: AFL, Language: Bash, Dialect: Gujarati

#284 translation: add translation reviews for Atom, AFL, and Bash in gujar…
  locale/gu.yml
Labels: Dialect: Gujarati

#287 Bengali Translation
  README.md
  locale/bn.yml
Labels: Language: Python, 🌍 Opportunity: Translation, Dialect: Bengali

#285 Telugu translation for Python Built in key words
  locale/te.yml
Labels: Language: Python, 🌍 Opportunity: Translation, Dialect: Telugu
