Repository legesher/legesher-translations, pull requests merged in 2021-10, with the labels that each got.

#216 Reviewed JavaScript
  locale/hi.yml
Labels: Hacktoberfest, 🌍 Opportunity: Translation, Language: JavaScript, Dialect: Hindi

#217 add gujarati translation for RUBY
  locale/gu.yml
Labels: Hacktoberfest, Language: Ruby, 🌍 Opportunity: Translation, Dialect: Gujarati

#219 Added Review on Indonesian Translation
  locale/id.yml
Labels: Language: Python, Hacktoberfest, 🌍 Opportunity: Translation, Dialect: Indonesian

#221 fix: Review Dialect: Arabic (Python)
  locale/ar.yml
Labels: Language: Python, Hacktoberfest, 🌍 Opportunity: Translation, Dialect: Arabic

#222 Add/Modify Hindi Translation
  locale/hi.yml
Labels: Hacktoberfest, 🌍 Opportunity: Translation, Language: Atom, Language: Agda, Language: AFL, Language: Bash, Language: C, Dialect: Hindi

#223 Reviewed python Built in function.
  locale/gu.yml
Labels: Language: Python, Hacktoberfest, 🌍 Opportunity: Translation, Dialect: Gujarati

#224 review: Telugu translation
  locale/te.yml
Labels: Language: Python, Hacktoberfest, 🌍 Opportunity: Translation, Dialect: Telugu

#225 Added Atom Keyword Hindi Translation Reviews
  locale/hi.yml
Labels: Hacktoberfest-Accepted, 🌍 Opportunity: Translation, Language: Atom, Dialect: Hindi

#226 Review Ukrainian translation
  locale/uk.yml
Labels: Language: Python, Hacktoberfest-Accepted, Dialect: Ukrainian, 🌍 Opportunity: Translation

#230 Fix the profile url in Readme.md
  README.md
Labels: Hacktoberfest-Accepted, 🖋 Opportunity: Content
