Repository legesher/legesher-translations, pull requests merged in 2021-01, with the labels that each got.

#188 docs: Adds Azerbiajani and Danish to Current Development in README
  .all-contributorsrc
  README.md
Labels: 📖 Opportunity: Documentation

#190 Added Swahili Translations
  locale/sw.yml
Labels: Dialect: Swahili, Language: Python, 🌍 Opportunity: Translation

#194 Swahili translation
  .all-contributorsrc
  README.md
Labels: Dialect: Swahili, Language: Python, 📖 Opportunity: Documentation

#196 Added new reviews on Gujarati translations
  locale/gu.yml
Labels: Dialect: Gujarati, Language: Python, 🌍 Opportunity: Translation
