Repository legesher/legesher-translations, pull requests merged in 2023-10, with the labels that each got.

#308 Telugu translation review
  locale/te.yml
Labels: Language: Python, 🌍 Opportunity: Translation, Dialect: Telugu

#310 Review Language: Telugu (Python)
  locale/te.yml
Labels: Language: Python, Hacktoberfest-Accepted, 🌍 Opportunity: Translation, Dialect: Telugu

#311 Reviewed Hindi-translations (python- keywords and Inbuilt functions)
  locale/hi.yml
Labels: Language: Python, Hacktoberfest-Accepted, 🌍 Opportunity: Translation, Dialect: Hindi
